### ISSUE TITLE
Feedly can't parse feeds

### ISSUE THREAD

**Issue by jnyrup** [cbenard/comicfeeds#1]
For at least the Dilbert feed neither the rss nor the atom feed validates, so Feedly can't parse them.
The rss feed works if the `xmlns` attribute is removed from the `description` tags.

**Comment by LongHairedHacker** [comment]
I have a similar issue with the owncloud news app.
The rss feed for Dilbert works, the atom feed doesn't.

**Comment by cbenard** [comment]
Feedly parses it now but you may need to add a query string like ?something=whatever to the end of the URL to defeat Feedly caching. If you don't, you will probably see new images starting tomorrow. Fixed in 5ec6067.

**Comment by LongHairedHacker** [comment]
I can confirm that the atom also works in owncloud now.
Thanks for fixing it.
